# Generated by Django 5.0 on 2023-12-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
